# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apps', '0003_auto_20170112_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='created',
        ),
    ]
